title:       "David Trick's Portfolio"
baseURL:     "https://trickyd9.github.io/portfolio"

docsDir:    "public"

subtitle:    "Portfolio"
description: "A showcase of a few of my projects, skills, and experience."

repo:        "https://github.com/trickyd9/portfolio"
